user-create:
  role: IamHelloWorldLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/create/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsHelloWorldTopic
    MONGO_DATABASE_URI: ${ssm:/hello-world/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/hello-world/databases/MONGO_NAME}
    CRYPTO_SECRET_KEY: ${ssm:/hello-world/crypto/SECRET_KEY}
    CRYPTO_SECRET_IV: ${ssm:/hello-world/crypto/SECRET_IV}
  events:
    - httpApi:
        method: POST
        path: /helloWorld/users

user-notify-registered:
  role: IamHelloWorldLambdaAccessRole
  handler: src/services/users/infrastructure/functions/sns/notifRegistered/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/hello-world/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/hello-world/databases/MONGO_NAME}
    SES_EMAIL_FROM: ${ssm:/hello-world/mailing/SES/SES_EMAIL_FROM}
  events:
    - sns:
        arn: !Ref EventBusSnsHelloWorldTopic
        topicName: ${self:custom.constants.HELLO_WORLD.SNS_TOPIC}
        filterPolicy:
          event_type:
            - 'soymichel-dev.hello-world.v1.user.created'

user-get-all:
  role: IamHelloWorldLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/getAll/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/hello-world/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/hello-world/databases/MONGO_NAME}
  events:
    - httpApi:
        method: GET
        path: /helloWorld/users
        authorizer:
          id: ${cf:core-${self:provider.stage}.CoreApiGatewayV2AuthorizerId}
          type: request

user-remove:
  role: IamHelloWorldLambdaAccessRole
  handler: src/services/users/infrastructure/functions/http/remove/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsHelloWorldTopic
    MONGO_DATABASE_URI: ${ssm:/hello-world/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/hello-world/databases/MONGO_NAME}
  events:
    - httpApi:
        method: DELETE
        path: /helloWorld/users/{userId}

user-notify-removed:
  role: IamHelloWorldLambdaAccessRole
  handler: src/services/users/infrastructure/functions/sns/notifRemoved/handler.handler
  environment:
    SES_EMAIL_FROM: ${ssm:/hello-world/mailing/SES/SES_EMAIL_FROM}
  events:
    - sns:
        arn: !Ref EventBusSnsHelloWorldTopic
        topicName: ${self:custom.constants.HELLO_WORLD.SNS_TOPIC}
        filterPolicy:
          event_type:
            - 'soymichel-dev.hello-world.v1.user.removed'
