category-create:
  role: IamTasksLambdaAccessRole
  handler: src/services/categories/infrastructure/functions/http/create/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: POST
        path: /tasks/categories

category-get-all:
  role: IamTasksLambdaAccessRole
  handler: src/services/categories/infrastructure/functions/http/all/handler.handler
  environment:
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: GET
        path: /tasks/categories
