Resources:
  EventBusSnsCoreTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:custom.constants.CORE.SNS_TOPIC}
  EventBusSnsCoreTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: EventBusSnsCoreTopicPolicyId
        Version: '2012-10-17'
        Statement:
        - Sid: EventBusSnsCoreTopicPolicySidSelf
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::${self:custom.environment.AWS_ACCOUNT_ID}:root
          Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
          Resource: !Ref EventBusSnsCoreTopic
      Topics:
        - !Ref EventBusSnsCoreTopic

Outputs:
  EventBusSnsCoreTopicArn:
    Value:
      Ref: EventBusSnsCoreTopic
    Export:
      Name: EventBusSnsCoreTopicArn
  EventBusSnsCoreTopicName:
    Value:  ${self:custom.constants.HELLO_WORLD.SNS_TOPIC}
    Export:
      Name: EventBusSnsCoreTopicName
