Resources:
  EventBusSnsAccountTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${self:custom.constants.ACCOUNT.SNS_TOPIC}
  EventBusSnsAccountTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref EventBusSnsAccountTopic
      PolicyDocument:
        Id: EventBusSnsAccountTopicPolicyId
        Version: '2012-10-17'
        Statement:
        - Sid: EventBusSnsAccountTopicPolicySidSelf
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::${self:custom.environment.AWS_ACCOUNT_ID}:root
          Action:
            - SNS:GetTopicAttributes
            - SNS:SetTopicAttributes
            - SNS:AddPermission
            - SNS:RemovePermission
            - SNS:DeleteTopic
            - SNS:Subscribe
            - SNS:ListSubscriptionsByTopic
            - SNS:Publish
            - SNS:Receive
          Resource: !Ref EventBusSnsAccountTopic

Outputs:
  EventBusSnsAccountTopicArn:
    Value:
      Ref: EventBusSnsAccountTopic
    Export:
      Name: EventBusSnsAccountTopicArn
  EventBusSnsAccountTopicName:
    Value:  ${self:custom.constants.ACCOUNT.SNS_TOPIC}
    Export:
      Name: EventBusSnsAccountTopicName
