task-create:
  role: IamTasksLambdaAccessRole
  handler:  src/services/tasks/infrastructure/functions/http/create/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsTasksTopic
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: POST
        path: /tasks

task-all:
  role: IamTasksLambdaAccessRole
  handler: src/services/tasks/infrastructure/functions/http/all/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsTasksTopic
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: GET
        path: /tasks

task-state-update:
  role: IamTasksLambdaAccessRole
  handler: src/services/tasks/infrastructure/functions/http/updateState/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsTasksTopic
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: PATCH
        path: /tasks/{taskId}
