task-create:
  role: IamTasksLambdaAccessRole
  handler:  src/services/tasks/infrastructure/functions/http/create/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsTasksTopic
    MONGO_DATABASE_URI: ${ssm:/tasks/databases/MONGO_URI}
    MONGO_DATABASE_NAME: ${ssm:/tasks/databases/MONGO_NAME}
  events:
    - httpApi:
        method: POST
        path: /tasks
