ping-get:
  handler: src/services/ping/infrastructure/functions/http/get/handler.handler
  environment:
    SNS_TOPIC_ARN: !Ref EventBusSnsAccountTopic
  events:
    - httpApi:
        method: GET
        path: /account/ping
